// Test script for the new POST /videos/process endpoint
import fetch from 'node-fetch';

const BASE_URL = 'http://localhost:4000';
// Using a fresh JWT token generated by generate_test_token.js
const JWT_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdC11c2VyQGplc3QtdGVzdHMuY29tIiwibHQiOm51bGwsImlhdCI6MTc1ODg2NjIyNywiZXhwIjoxNzU4ODY3MTI3fQ.qPWBGCxRS5DJ3c_lRCeBnKTe2YbdFtJ2VnigT_ezJcU';

async function testVideoProcess() {
    try {
        console.log('Testing POST /videos/process endpoint...');
        
        const testData = {
            videoId: 'dQw4w9WgXcQ', // Rick Astley - Never Gonna Give You Up
            title: 'Test Video Title',
            description: 'Test video description for transcript extraction'
        };

        const response = await fetch(`${BASE_URL}/videos/process`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${JWT_TOKEN}`
            },
            body: JSON.stringify(testData)
        });

        const result = await response.json();
        
        console.log('Status:', response.status);
        console.log('Response:', JSON.stringify(result, null, 2));
        
        if (response.ok) {
            console.log('✅ Video processed successfully!');
        } else {
            console.log('❌ Error processing video');
        }
    } catch (error) {
        console.error('❌ Test failed:', error.message);
    }
}

// Run the test
testVideoProcess();